const USER_CREATE = "USER_CREATE";
const USER_EDIT = "USER_EDIT";
const USER_DELETE = "USER_DELETE";
const USERS_LIST = "USERS_LIST";
const USER_LIST_FILTER = "USER_LIST_FILTER";
const GET_USERS_LIST = "GET_USERS_LIST";
const USER_LIST_SORT = "USER_LIST_SORT";

const types = {
  USER_CREATE,
  USER_EDIT,
  USER_DELETE,
  USERS_LIST,
  USER_LIST_FILTER,
  GET_USERS_LIST,
  USER_LIST_SORT,
};

export default types;
