const GAME_CREATE = "GAME_CREATE";
const GAME_ROUND = "GAME_ROUND";
const GAME_DELETE = "GAME_DELETE";
const GAME_LIST = "GAME_LIST";
const GAME_LIST_FILTER = "GAME_LIST_FILTER";
const GET_GAMES_LIST = "GET_GAMES_LIST";
const GAME_LIST_SORT = "GAME_LIST_SORT";

const types = {
  GAME_CREATE,
  GAME_ROUND,
  GAME_DELETE,
  GAME_LIST,
  GAME_LIST_FILTER,
  GET_GAMES_LIST,
  GAME_LIST_SORT,
};

export default types;
